puts "THE STUDENTS OF VILLAINS ACADEMY"
puts "--------------------------------"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Jeoffrey Baratheon"
puts "Norman Bates"